INSERT INTO COZINHA (id, nome) values(1, 'Tailandesa');
INSERT INTO COZINHA (id, nome) values(2, 'Brasileira');
INSERT INTO RESTAURANTE (nome, taxa_frete, cozinha_codigo) values('Habibs', 10, 1);
INSERT INTO RESTAURANTE (nome, taxa_frete, cozinha_codigo) values('Giraffas', 10, 2);
INSERT INTO RESTAURANTE (nome, taxa_frete, cozinha_codigo) values('Grilleto', 10, 2);
INSERT INTO RESTAURANTE (nome, taxa_frete, cozinha_codigo) values('Mcdonalds', 10, 2);
INSERT INTO RESTAURANTE (nome, taxa_frete, cozinha_codigo) values('Bobs', 10, 1);
INSERT INTO RESTAURANTE (nome, taxa_frete, cozinha_codigo) values('Divino', 10, 1);
INSERT INTO ESTADO(id, nome) values (1, 'Sao Paulo');
INSERT INTO ESTADO(id, nome) values (2, 'Minas Gerais');
INSERT INTO ESTADO(id, nome) values (3, 'Rio de Janeiro');
INSERT INTO ESTADO(id, nome) values (4, 'Bahia');
INSERT INTO CIDADE(nome, estado_id) values ('Taboao da Serra', 1);
INSERT INTO CIDADE(nome, estado_id) values ('Belo Horizonte', 2);
INSERT INTO CIDADE(nome, estado_id) values ('Rio de Janeiro', 3);
INSERT INTO CIDADE(nome, estado_id) values ('Salvador', 4);